mode: "local"

db:
  user: root
  password: root
  name: snippetbox
  host: localhost
  port: 3306

http_server:
  port: 8000
  host: localhost
  idle_timeout: "30s"
  read_timeout: "5s"
  write_timeout: "10s"